all:
	gcc -o cidr.bin cidr.c
	gcc -o recapAdresse.bin recapAdresse.c -lm
	gcc -o divisionSousReseau.bin divisionSousReseau.c -lm
	gcc -Wall -Wextra -o VLSM.bin VLSM.c

VLSM :
	gcc -Wall -Wextra -o VLSM.bin VLSM.c -lm
